stages:
  - build
  - test

build:
  stage: build
  image: node:10-alpine 
  script:
    - echo "Building..."
    - npm i

test:
  stage: test
  image: node:10-alpine 
  script:
    - npm i
    - npm run test